language: php

sudo: required

env:
    matrix:
        - PHP_VERSION: "7.1"
    global:
        - DATABASE_HOST=127.0.0.1
        - DATABASE_USER=root
        - DATABASE_PASSWORD=
        - REDIS_HOST=127.0.0.1

services:
    - mysql
    - redis-server
    - docker

before_install:
    - docker run --rm --detach --name "php${PHP_VERSION}" -v "$(pwd):/app" "quay.io/continuouspipe/php${PHP_VERSION}-nginx:latest" sleep infinity
    - docker exec "php${PHP_VERSION}" bash -c 'set -e;
      apt-get update;
      apt-get install -y librabbitmq-dev curl bzip2 php-amqp;
      curl -o /tmp/shellcheck.tar.bz2 https://s3.amazonaws.com/travis-blue-public/binaries/ubuntu/14.04/x86_64/shellcheck-0.4.5.tar.bz2;
      tar -C /tmp -xjf /tmp/shellcheck.tar.bz2;
      mv /tmp/shellcheck-0.4.5/shellcheck /usr/local/bin/'

install:
    - docker exec "php${PHP_VERSION}" bash -c 'set -e;
      cd /app;
      pushd api && composer install && popd'

script:
    - docker exec "php${PHP_VERSION}" bash -c 'set -e;
      cd /app;
      source .env.dist;
      pushd api/;
      vendor/bin/phpspec --no-interaction run;
      vendor/bin/phpunit;
      find .. -type f \( -executable -or -name "*.sh" \) ! -path "*/vendor/*" ! -path "*/.git/*" ! -path "*/api/bin/console" ! -path "*/api/bin/symfony_requirements" -exec shellcheck --exclude SC1091 {} +;
      vendor/bin/behat --profile=domain -fprogress;
      bin/console doctrine:database:create --no-interaction;
      bin/console doctrine:migrations:migrate --no-interaction;
      vendor/bin/behat --profile=smoke -fprogress;
      popd'

after_script:
    - docker stop php7.1

after_success:
    - |
      if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" &&
        docker-compose -f docker-compose.yml -f docker-compose.images.yml build && docker-compose -f docker-compose.yml -f docker-compose.with-images.yml push;
      fi
