version: '2.1'

services:
    api:
        build:
            context: ./api
        environment:
            - DATABASE_HOST=database
            - DATABASE_USER=continuouspipe
            - DATABASE_PASSWORD=continuouspipe
            - DATABASE_NAME=continuouspipe
            - REDIS_HOST=redis
            - LOGSTREAM_URL=https://logstream
            - K8S_WATCHER_URL=http://k8s-watcher
        depends_on:
            - database
            - redis
            - logstream
            - rabbitmq
        healthcheck:
            test: curl -f http://localhost
            interval: 30s
            timeout: 30s
            retries: 30

    worker:
        build:
            context: ./api
        command: /usr/local/bin/worker
        depends_on:
            api:
                condition: service_healthy
        environment:
            - DATABASE_HOST=database
            - DATABASE_USER=continuouspipe
            - DATABASE_PASSWORD=continuouspipe
            - DATABASE_NAME=continuouspipe
            - REDIS_HOST=redis
            - LOGSTREAM_URL=https://logstream
            - K8S_WATCHER_URL=http://k8s-watcher

    ui:
        build:
            context: ./ui

    logstream:
        build:
            context: ./logstream

    kube-proxy:
        build:
            context: ./kube-proxy
        depends_on:
            - api

    k8s-watcher:
        build:
            context: ./k8s-watcher
        environment:
            - REDIS_HOST=redis
            - KUBE_PROXY_HOSTNAME=kube-proxy
        depends_on:
            - kube-proxy

    database:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=continuouspipe
            - MYSQL_USER=continuouspipe
            - MYSQL_PASSWORD=continuouspipe
        expose:
            - 3306

    redis:
        image: redis:alpine
        expose:
            - 6379

    rabbitmq:
        image: rabbitmq:3-management
        expose:
            - 5672
            - 15672
