version: '2.1'

services:
    api:
        build:
            args:
                - APP_ENV=dev
        ports:
            - 81:80
        environment:
            WEB_HTTP: "true"
            SYMFONY_ENV: dev # Uses the `dev` Symfony environment
            SYMFONY_WEB_APP_ENV_REWRITE: "true" # Uses the `app_dev.php` endpoint
        volumes:
            - ./api:/app
            - ./runtime/keys:/runtime/keys
            - ~/.kube/config:/runtime/kube-config
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - .env

    worker:
        build:
            args:
                - APP_ENV=dev
        environment:
            SYMFONY_ENV: dev
            SKIP_COMPOSER: "true"
            GRANT_DOCKER_DAEMON: "true"
            NUM_OF_WORKERS: "2"
        volumes:
            - ./api:/app
            - ./runtime/keys:/runtime/keys
            - ~/.kube/config:/runtime/kube-config
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - .env

    ui:
        ports:
            - 80:80
            - 35729:35729
        build:
            dockerfile: ./Dockerfile.dev
        volumes:
            - ./ui/app:/app/app
        env_file:
            - .env
        environment:
            - KUBE_PROXY_URL=ws://localhost:82

    logstream:
        volumes:
            - ./logstream/src:/app/src
            - ./runtime/keys:/runtime/keys
        env_file:
            - .env

    kube-proxy:
        environment:
            - KUBE_PROXY_API_URL=http://api
            - KUBE_PROXY_LISTEN_ADDRESS=http://0.0.0.0:80
        env_file:
            - .env
        ports:
            - 82:80

    k8s-watcher:
        env_file:
            - .env
        environment:
            - KUBE_PROXY_SCHEME=ws
        volumes:
            - ./k8s-watcher/src:/app/src
            - ./runtime/keys:/runtime/keys

    rabbitmq:
        ports:
            - 15672:15672
            - 5672:5672

    tunnel:
        image: wernight/ngrok
        command: ngrok http api:80
        ports:
            - 4040:4040
