version: '2'

services:
    api: &API_DEFINITION
        build:
            context: ./api
        volumes:
            - ./api:/app
            - ./runtime/keys:/app/var/keys
        environment:
            - DATABASE_HOST=database
            - DATABASE_USER=continuouspipe
            - DATABASE_PASSWORD=continuouspipe
            - DATABASE_NAME=continuouspipe
            - REDIS_HOST=redis
            - LOGSTREAM_URL=https://logstream
        env_file:
            - .env
        depends_on:
            - database
            - redis
            - logstream
            - rabbitmq

    worker:
        <<: *API_DEFINITION
        command: /usr/local/bin/worker

    ui:
        build:
            context: ./ui
        volumes:
            - ./ui/app:/app/app
        env_file:
            - .env

    logstream:
        build:
            context: ./logstream
        volumes:
            - ./logstream/src:/app/src
            - ./runtime/keys:/app/var/keys
        env_file:
            - .env

    database:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=continuouspipe
            - MYSQL_USER=continuouspipe
            - MYSQL_PASSWORD=continuouspipe
        expose:
            - 3306

    redis:
        image: redis:alpine
        expose:
            - 6379

    rabbitmq:
        image: rabbitmq:3-management
        expose:
            - 5672
            - 15672
