version: '2.1'

services:
    api:
        ports:
            - 81:80
        environment:
            WEB_HTTP: "true"
            SYMFONY_ENV: dev # Uses the `dev` Symfony environment
            SYMFONY_WEB_APP_ENV_REWRITE: "true" # Uses the `app_dev.php` endpoint

    worker:
        environment:
            SYMFONY_ENV: dev
            SKIP_COMPOSER: "true"

    ui:
        ports:
            - 80:80
            - 35729:35729
        build:
            dockerfile: ./Dockerfile.dev

    rabbitmq:
        ports:
            - 15672:15672
            - 5672:5672

    tunnel:
        image: wernight/ngrok
        command: ngrok http api:80
        ports:
            - 4040:4040
