apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-sentinel
spec:
  serviceName: "redis-sentinel-headless"
  replicas: 3
  template:
    metadata:
      labels:
        component-identifier: redis-sentinel
        redis-sentinel: "true"
        role: sentinel
    spec:
      containers:
      - name: sentinel
        image: quay.io/continuouspipe/redis3-highly-available:stable
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
