apiVersion: v1
kind: Service
metadata:
  labels:
    component-identifier: redis
    role: service
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    component-identifier: redis
