kind: Service
apiVersion: v1
metadata:
  name: cluster
  namespace: eventstore
spec:
  type: LoadBalancer
  selector:
    name: eventstore-node
  ports:
  - name: 'external-http'
    protocol: TCP
    port: 80
    targetPort: 2114
