apiVersion: v1
kind: PetSet
metadata:
  name: cluster
  namespace: eventstore
spec:
  serviceName: cluster
  replicas: 3
  template:
    metadata:
      labels:
        name: eventstore-node
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: es
          image: "docker.io/eventstore/eventstore:release-3.8.1"
          env:
            - name: EVENTSTORE_INT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EVENTSTORE_EXT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EVENTSTORE_INT_TCP_PORT
              value: "1111"
            - name: EVENTSTORE_EXT_TCP_PORT
              value: "1112"
            - name: EVENTSTORE_INT_HTTP_PORT
              value: "2113"
            - name: EVENTSTORE_EXT_HTTP_PORT
              value: "2114"
            - name: EVENTSTORE_CLUSTER_SIZE
              value: "3"
            - name: EVENTSTORE_CLUSTER_DNS
              value: "cluster.eventstore.svc.cluster.local"
            - name: EVENTSTORE_CLUSTER_GOSSIP_PORT
              value: "2114"
            - name: EVENTSTORE_GOSSIP_ALLOWED_DIFFERENCE_MS
              value: "600000"
            - name: EVENTSTORE_INT_HTTP_PREFIXES
              value: "http://*:2114/"
            - name: EVENTSTORE_EXT_HTTP_PREFIXES
              value: "http://*:2113/"
          ports:
            - containerPort: 2113
            - containerPort: 2114
            - containerPort: 1111
            - containerPort: 1112
          volumeMounts:
            - name: eventstore-node
              mountPath: /var/lib/eventstore
          livenessProbe:
            tcp:
              port: 2113
            initialDelaySeconds: 30
            timeoutSeconds: 1
  volumeClaimTemplates:
  - metadata:
      name: eventstore-node
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
