apiVersion: v1
kind: Service
metadata:
  labels:
    component-identifier: google-sql-proxy
  name: google-sql-proxy
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    component-identifier: google-sql-proxy
