apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    component-identifier: kube-resources-watcher
  name: kube-resources-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      component-identifier: kube-resources-watcher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component-identifier: kube-resources-watcher
      name: kube-resources-watcher
    spec:
      containers:
      - env:
        - name: CLUSTER_INCEPTION
          value: "true"
        - name: HTTP_ENDPOINT
          value: https://river.continuouspipe.io/managed/resources
        - name: HTTP_ENDPOINT_BEARER_TOKEN
          value: TO-BE-REPLACED
        - name: MINIMUM_UPDATE_INTERVAL
          value: "21600"
        image: quay.io/continuouspipe/kube-resources-watcher:v0.0.3
        imagePullPolicy: IfNotPresent
        name: kube-resources-watcher
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
      restartPolicy: Always
      schedulerName: default-scheduler
