ContinuousPipe\Pipe\DeploymentRequest:
    properties:
        target:
            type: ContinuousPipe\Pipe\DeploymentRequest\Target
        specification:
            type: ContinuousPipe\Pipe\DeploymentRequest\Specification
        notification:
            type: ContinuousPipe\Pipe\DeploymentRequest\Notification
