ContinuousPipe\Pipe\DeploymentRequest:
    properties:
        environmentName:
            type: string
            serialized_name: environmentName
        providerName:
            type: string
            serialized_name: providerName
        dockerComposeContents:
            type: string
            serialized_name: dockerComposeContents
        notificationCallbackUrl:
            type: string
            serialized_name: notificationCallbackUrl
        logId:
            type: string
            serialized_name: logId
