imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    router:
        resource: "%kernel.root_dir%/config/routing_test.yml"

web_profiler:
    toolbar: false
    intercept_redirects: false

continuous_pipe_security:
    cache: true

beberlei_metrics:
    collectors:
        statsd:
            type: 'null'

parameters:
    github_secret: '3216994be6ee462571feb2e0bfeedc5ab82152b4'

message:
    connections:
        default:
            debug: true
            driver:
                direct: ~
