imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    default_environment_expression: 'flow.uuid ~ "-" ~ code_reference.branch'
    firebase_service_account_path: '%kernel.root_dir%/var/firebase/continuous-pipe-firebase-adminsdk-57uln-abf9ce37fe.json'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        
        # see https://github.com/doctrine/DoctrineBundle/issues/351
        server_version: 5.6

        types:
            b64Object: ContinuousPipe\River\Infrastructure\Doctrine\Type\Base64Object
            datetime: ContinuousPipe\River\Infrastructure\Doctrine\Type\UTCDateTimeType
            uuid:  Ramsey\Uuid\Doctrine\UuidType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            ContinuousPipeRiverDto:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../src/ContinuousPipe/River/Infrastructure/Doctrine/Entity'
                prefix: ContinuousPipe\River\Infrastructure\Doctrine\Entity
            ContinuousPipeAtlassianAddon:
                type: xml
                is_bundle: false
                dir: '%kernel.root_dir%/../src/ContinuousPipe/AtlassianAddon/Infrastructure/Doctrine/Resources/config'
                prefix: ContinuousPipe\AtlassianAddon
            ContinuousPipeRiver:
                type: xml
                is_bundle: false
                dir: '%kernel.root_dir%/../src/ContinuousPipe/River/Infrastructure/Doctrine/Resources/config'
                prefix: ContinuousPipe

jms_serializer:
    metadata:
        directories:
            GitHubWebHook:
                namespace_prefix: "GitHub\\WebHook"
                path: "%kernel.root_dir%/../src/GitHub/WebHook/Resources/serializer"
            ContinuousPipeBuilder:
                namespace_prefix: "ContinuousPipe\\Builder"
                path: "%kernel.root_dir%/../src/ContinuousPipe/Builder/Resources/serializer"
            ContinuousPipeModel:
                namespace_prefix: "ContinuousPipe\\Model"
                path: "%kernel.root_dir%/../vendor/continuous-pipe/model/src/Resources/serializer"

lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%

continuous_pipe_security:
    authenticator_url: %authenticator_url%
    api_key: %authenticator_api_key%
    cache: true

fos_rest:
    body_converter:
        enabled: true

    view:
        view_response_listener: true

    format_listener:
        rules:
            - { path: '^/(_profiler|admin)', priorities: ['html'] }
            - { path: '^/$', priorities: ['html'], fallback_format: html, prefer_extension: false }
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }

    exception:
        messages:
            'ContinuousPipe\River\CodeRepository\CodeRepositoryException': true

sensio_framework_extra:
    view:    { annotations: false }
    request: { converters: true }

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: '*'
        allow_headers: ['accept', 'content-type', 'authorization', 'x-http-method-override']
        allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE']
        max_age: 3600
    paths:
        '^/': ~

event_bus:
    logging: ~

command_bus:
    logging: ~

log_stream:
    url: %logstream_url%
    strict_ssl: false

old_sound_rabbit_mq:
    connections:
        default:
            host:     %rabbitmq_host%
            port:     5672
            user:     %rabbitmq_user%
            password: %rabbitmq_password%
            vhost:    %rabbitmq_vhost%
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0

        stack:
            host:     %stack_rabbitmq_host%
            port:     5672
            user:     %stack_rabbitmq_user%
            password: %stack_rabbitmq_password%
            vhost:    %stack_rabbitmq_vhost%
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0

    producers:
        asynchronous_commands:
            connection:       default
            exchange_options: { name: %rabbitmq_queue_name%, type: direct }

        stack_user_activity:
            connection:       stack
            exchange_options: { name: user_activities, type: fanout }

simple_bus_rabbit_mq_bundle_bridge:
    commands:
        # this producer service is defined by OldSoundRabbitMqBundle,
        # its name is old_sound_rabbit_mq.%producer_name%_producer
        producer_service_id: old_sound_rabbit_mq.asynchronous_commands_producer

simple_bus_asynchronous:
    object_serializer_service_id: river.jms_serializer.object_serializer
    commands:
        logging: ~

csa_guzzle:
    profiler: %kernel.debug%

knp_paginator:
    # page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig

beberlei_metrics:
    collectors:
        statsd:
            type: statsd
            host: %statsd_host%
            port: %statsd_port%
            prefix: %statsd_prefix%.

tolerance:
    aop:
        enabled: true

        wrappers:
            - class: "ContinuousPipe\Security\Authenticator\HttpAuthenticatorClient"
              methods:
                  - getUserByUsername
                  - findBucketByUuid
                  - findTeamBySlug
                  - findAllTeams
              runner: tolerance.operation_runners.authenticator

    operation_runners:
        default:
            callback: ~

        null_placeholdered:
            placeholder:
                value: ~
                logger: logger

        array_placeholdered:
            placeholder:
                value: []
                logger: logger

        buffered:
            buffered:
                runner: tolerance.operation_runners.null_placeholdered

        builder:
            success_failure_metrics:
                publisher: tolerance.metrics.publisher.statsd
                namespace: river.outgoing.builder

        pipe:
            success_failure_metrics:
                publisher: tolerance.metrics.publisher.statsd
                namespace: river.outgoing.pipe

        authenticator:
            success_failure_metrics:
                publisher: tolerance.metrics.publisher.statsd
                namespace: river.outgoing.authenticator

        github:
            success_failure_metrics:
                publisher: tolerance.metrics.publisher.statsd
                namespace: river.outgoing.github

        slack:
            success_failure_metrics:
                publisher: tolerance.metrics.publisher.statsd
                namespace: river.outgoing.slack
                runner: tolerance.operation_runners.null_placeholdered

        firebase:
            success_failure_metrics:
                publisher: tolerance.metrics.publisher.statsd
                namespace: river.outgoing.firebase
                runner: tolerance.operation_runners.null_placeholdered

    metrics:
        collectors:
            -
                type: rabbitmq
                namespace: river.queue
                options:
                    host: %rabbitmq_host%
                    port: %rabbitmq_management_port%
                    username: %rabbitmq_user%
                    password: %rabbitmq_password%
                    vhost: %rabbitmq_vhost%
                    queue: %rabbitmq_queue_name%

        publishers:
            hosted_graphite:
                type: hosted_graphite
                operation_runner: tolerance.operation_runners.buffered
                options:
                    server: %hosted_graphite_server%
                    port: %hosted_graphite_port%
                    api_key: %hosted_graphite_api_key%

            statsd:
                type: beberlei
                operation_runner: tolerance.operation_runners.buffered
                options:
                    service: beberlei_metrics.collector.statsd
                    auto_flush: true

        command:
            publisher: tolerance.metrics.publisher.hosted_graphite

        request:
            namespace: river.api.http.request
            publisher: tolerance.metrics.publisher.statsd

    tracer:
        service_name: River
        operation_runner: tolerance.operation_runners.buffered

        zipkin:
            http:
                base_url: %zipkin_base_url%

        rabbitmq:
            consumers:
                - simple_bus.rabbit_mq_bundle_bridge.commands_consumer

worker:
    service: simple_bus.rabbit_mq_bundle_bridge.commands_consumer
    tideways:
        api_key: %tideways_api_key%
