imports:
    - { resource: config.yml }

framework:
    validation:
        cache: validator.mapping.cache.apc
    profiler:
        enabled: true
        only_exceptions: false

doctrine:
    orm:
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

web_profiler:
    toolbar: false

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: info
            handler:      grouped_main
        sentry:
            type:  raven
            dsn:   %sentry_dsn%
            level: notice
        grouped_main:
            type:    group
            members: [sentry, error_log]
        error_log:
            type:  error_log
            level: debug
        console:
            type:    group
            members: [sentry, console_display]
        console_display:
            type:  console
