imports:
    - { resource: config.yml }

framework:
    validation:
        cache: validator.mapping.cache.doctrine.apc

doctrine:
    orm:
        metadata_cache_driver: apcu
        result_cache_driver: apcu
        query_cache_driver: apcu

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: info
            handler:      grouped_main
        sentry:
            type:  raven
            dsn:   %sentry_dsn%
            level: notice
        grouped_main:
            type:    group
            members: [sentry, error_log]
        error_log:
            type:  error_log
            level: debug
        console:
            type:  console
