app:
    resource: "@AppBundle/Controller/"
    type:     annotation

builder:
    resource: "@BuilderBundle/Controller/"
    type:     annotation
    prefix: /builder

admin:
    resource: "@AdminBundle/Controller/"
    type: annotation
    prefix: /admin

atlassian:
    resource: "@AtlassianAddonBundle/Controller/"
    type: annotation
    prefix: /connect/service/bitbucket/addon

development_environment:
    resource: "@DevelopmentEnvironmentBundle/Controller/"
    type: annotation
    prefix: /
