security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        authenticator:
            id: security.user_provider

        in_memory:
            memory:
                users:
                    admin:
                        password: %admin_password%
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            http_basic: ~
            provider: in_memory

        api:
            pattern:   ^/
            stateless: true
            lexik_jwt: ~
            anonymous: ~
            provider: authenticator

    access_control:
        # TODO: Secure with GitHub IPs
        - { path: ^/web-hook/github/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/github/integration/webhook$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # TODO: Secure with local IPs
        - { path: ^/builder/notification, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pipe/notification, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/runner/notification, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # TODO: Secure with Atlassian's IPs
        - { path: ^/connect/service/bitbucket/addon/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Required by GCE healthchecks
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
