security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        authenticator:
            id: app.security.user_provider

        api_key:
            id: security.api_key.user_provider

        in_memory:
            memory:
                users:
                    admin:
                        password: "%admin_password%"
                        roles: 'ROLE_ADMIN'
                    '/C=UK/ST=London/O=ContinuousPipe/CN=FeatureTimeline':
                        roles: ['ROLE_SYSTEM_FEATURE_TIMELINE']
                        password: ''
                    continuouspipe_builder_for_sources:
                        roles: ['ROLE_DOWNLOAD_CODE_ARCHIVE']
                    'system:resources_usage_updater':
                        roles: ['ROLE_RESOURCE_USAGE_CREATOR']
                    'system:river':
                        roles: ['ROLE_SYSTEM']

        chain:
            chain:
                providers:
                    - in_memory
                    - authenticator
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            http_basic: ~
            provider: in_memory

        auth:
            pattern: ^/auth
            provider: authenticator
            anonymous: true
            oauth:
                resource_owners:
                    github: "/auth/login/check-github"
                    google: "/auth/login/check-google"
                    bitbucket: "/auth/login/check-bitbucket"
                login_path: /auth/login
                use_forward: false
                failure_path: /auth/login
                require_previous_session: false
                check_path: /auth/login_check
                oauth_user_provider:
                    service: app.security.user_provider

            remember_me:
                secret:   '%secret%'
                lifetime: 31536000 # 1 year in seconds
                path:     /auth/
                always_remember_me: true

            logout:
                path:           /auth/logout
                target:         /auth/login

        api:
            pattern:   ^/
            stateless: true
            x509:
                user: DN
                provider: in_memory
            lexik_jwt: ~
            anonymous: ~
            provider: chain
            simple_preauth:
                authenticator: security.api_key_authenticator
                provider: api_key


    access_control:
        # Auth pages
        - { path: ^/auth/(login|connect), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/billing-redirection, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/account/invitation/[\d-]+/accept$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/authenticate$, roles: IS_AUTHENTICATED_REMEMBERED }

        # TODO: Secure with GitHub IPs
        - { path: ^/web-hook/github/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/github/integration/webhook$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/github/flows/([0-9-]+)/installation-token, roles: [ ROLE_SYSTEM_FEATURE_TIMELINE ]}

        # TODO: Secure with local IPs or API keys
        - { path: ^/builder/notification, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pipe/notification, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/runner/notification, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # TODO: Remove this deprecated path; that is also a security hole
        - { path: ^/github/flows, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/flows/([a-z0-9-]+)/source-code/archive, methods: [GET], roles: ROLE_DOWNLOAD_CODE_ARCHIVE }

        # TODO: Secure with Atlassian's IPs
        - { path: ^/connect/service/bitbucket/addon/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Managed services
        - { path: ^/managed/resources$, roles: ROLE_RESOURCE_USAGE_CREATOR }

        # GCB build complete endpoint
        - { path: ^/builder/complete/([0-9a-z-]+)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # Required by GCE healthchecks
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
