security:
    providers:
        authenticator:
            id: security.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        api:
            pattern:   ^/
            stateless: true
            lexik_jwt: ~
            anonymous: ~

    access_control:
        - { path: ^/github/payload$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
