security:
    providers:
        authenticator:
            id: security.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        api:
            pattern:   ^/
            stateless: true
            lexik_jwt: ~
            anonymous: ~

    access_control:
        # TODO: Secure with GitHub IPs
        - { path: ^/web-hook/github/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        # TODO: Secure with local IPs
        - { path: ^/builder/notification, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pipe/notification, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/runner/notification, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
