ContinuousPipe\Pipe\DeploymentRequest:
    properties:
        target:
            - Valid: ~
            - NotNull: ~
        specification:
            - Valid: ~
            - NotNull: ~
        credentialsBucket:
            - NotBlank: ~
