ContinuousPipe\Security\Credentials\Cluster:
    properties:
        identifier:
            - NotBlank: ~
            - Regex:
                  pattern: '/^([a-z0-9_-]{3,255})$/'
                  message: The identifier should only contain letters, number, `_` or `-` and be between 3 and 255 characters.
