ContinuousPipe\Security\Credentials\Cluster\Kubernetes:
    constraints:
        - Callback: validate

    properties:
        address:
            - NotBlank: ~
            - Url: ~
        version:
            - NotBlank: ~
