ContinuousPipe\Builder\BuildStepConfiguration:
    constraints:
        - Expression:
            expression: "this.getArchive() != null || this.getRepository() != null"
            message: "A build request needs to have source: either a repository or an archive"
    properties:
        readArtifacts:
            - Valid: ~
        writeArtifacts:
            - Valid: ~
