ContinuousPipe\User\DockerRegistryCredentials:
    properties:
        username:
            - NotBlank: ~
        password:
            - NotBlank: ~
        email:
            - NotBlank: ~
        serverAddress:
            - NotBlank: ~
