ContinuousPipe\Builder\Request\BuildRequest:
    properties:
        credentialsBucket:
            - NotBlank: ~
        steps:
            - Valid: ~
        engine:
           - Choice: { choices: [docker, gcb], message: Choose a valid engine. }
