ContinuousPipe\Security\Credentials\Cluster\Kubernetes:
    properties:
        address:
            - NotBlank: ~
        version:
            - NotBlank: ~
        username:
            - NotBlank: ~
        password:
            - NotBlank: ~
