api:
    build: .
    command: [node, /app/api.js]
    links:
        - redis
    volumes:
        - .:/app
    expose:
        - 80
    ports:
        - "8081:80"
    environment:
        PORT: 80
        SENTRY_DSN: http://c6f81870b55f41d482a8300ec7ff0d42@sentry.tools.sroze.io/15
        REDIS_HOST: redis
        FIREBASE_DATABASE_NAME: continuouspipe-watch-logs
        FIREBASE_SERVICE_ACCOUNT: 
        STATSD_HOST: statsd.hostedgraphite.com
        STATSD_PORT: 8125
        STATSD_PREFIX: eeea7603-a2d5-4d51-adc4-0c3f8f042b28.k8s-watcher.
        KUBE_PROXY_HOSTNAME: kube-proxy-staging.continuouspipe.io

worker:
    build: .
    command: [node, /app/worker.js]
    links:
        - redis
    volumes:
        - .:/app
    environment:
        SENTRY_DSN: http://c6f81870b55f41d482a8300ec7ff0d42@sentry.tools.sroze.io/15
        REDIS_HOST: redis
        FIREBASE_DATABASE_NAME: continuouspipe-watch-logs
        FIREBASE_SERVICE_ACCOUNT: 
        STATSD_HOST: statsd.hostedgraphite.com
        STATSD_PORT: 8125
        STATSD_PREFIX: eeea7603-a2d5-4d51-adc4-0c3f8f042b28.k8s-watcher.
        KUBE_PROXY_HOSTNAME: kube-proxy-staging.continuouspipe.io

redis:
    image: redis

#stats:
#    build: .
#    command: /app/stats.js
#    environment:
#        STATSD_HOST: statsd.hostedgraphite.com
#        STATSD_PORT: 8125
#        STATSD_PREFIX: eeea7603-a2d5-4d51-adc4-0c3f8f042b28.k8s-watcher
