pipelines:
    - name: Staging
      condition: code_reference.branch == 'master'
      tasks: [ images, deployment ]
    - name: Production
      condition: code_reference.branch == 'production'
      tasks: [ images, deployment ]
    - name: Pull-requests
      condition: code_reference.branch not in ['master', 'production']
      tasks: [ images, deployment ]

variables:
    - name: AUTHENTICATOR_API_URL
      condition: code_reference.branch == 'production'
      value: https://authenticator.continuouspipe.io
    - name: RIVER_API_URL
      condition: code_reference.branch == 'production'
      value: https://river.continuouspipe.io
    - name: KUBE_PROXY_HOSTNAME
      value: kube-proxy.continuouspipe.io
      condition: code_reference.branch == 'production'

    - name: AUTHENTICATOR_API_URL
      condition: code_reference.branch != 'production'
      value: https://authenticator-staging.continuouspipe.io
    - name: RIVER_API_URL
      condition: code_reference.branch != 'production'
      value: https://river-staging.continuouspipe.io
    - name: KUBE_PROXY_HOSTNAME
      value: kube-proxy-staging.continuouspipe.io
      condition: code_reference.branch != 'production'
tasks:
    images:
        build:
            services:
                ui:
                    steps:
                        - docker_file_path: ./docker/build/Buildfile
                          write_artifacts:
                              - name: dist
                                path: /app/dist
                        - docker_file_path: ./docker/build/Productionfile
                          image: inviqasession/cp-river-ui
                          read_artifacts:
                              - name: dist
                                path: /dist

    deployment:
        deploy:
            cluster: ${CLUSTER}
            environment:
                name: '"ui-" ~ code_reference.branch'

            services:
                ui:
                    endpoints:
                        -
                            name: https
                            type: NodePort
                            ssl_certificates:
                                -
                                    name: continuouspipeio
                                    cert: ${WILDCARD_SSL_CERT}
                                    key: ${WILDCARD_SSL_KEY}

                    specification:
                        environment_variables:
                            - name: AUTHENTICATOR_API_URL
                              value: ${AUTHENTICATOR_API_URL}
                            - name: LOG_STREAM_URL
                              value: https://logstream.continuouspipe.io
                            - name: PIPE_API_URL
                              value: https://pipe.continuouspipe.io
                            - name: RIVER_API_URL
                              value: ${RIVER_API_URL}
                            - name: SENTRY_DSN
                              value: ${SENTRY_DSN}
                            - name: KUBE_PROXY_HOSTNAME
                              value: ${KUBE_PROXY_HOSTNAME}
