build:
    image: docker.io/sroze/php-stack
    environment:
        - DATABASE_HOST=127.0.0.1

    commands:
        - composer config -g github-oauth.github.com d5e0f6092daa83a33bcb439bfa88ecb87dc4c691
        - composer install

        # Domain tests
        - bin/phpspec run
        - bin/behat -fprogress

        # Smoke tests
        - app/console doctrine:migrations:migrate --no-interaction
        - bin/behat -f progress --profile=smoke

cache:
    mount:
        - vendor

compose:
    database:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=river
            - MYSQL_USER=river
            - MYSQL_PASSWORD=river

