build:
    image: docker.io/sroze/php-stack:7.0
    environment:
        - DATABASE_HOST=127.0.0.1
        - REDIS_HOST=127.0.0.1
        - COMPOSER_HOME=/drone/composer-cache

    commands:
        - composer config -g github-oauth.github.com d5e0f6092daa83a33bcb439bfa88ecb87dc4c691
        - composer install

        # Domain tests
        - bin/phpspec run
        - bin/phpunit -c app
        - bin/behat -fprogress

        # Smoke tests
        - app/console doctrine:migrations:migrate --no-interaction
        - bin/behat -f progress --profile=smoke

cache:
    mount:
        - /drone/composer-cache

compose:
    database:
        image: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=river
            - MYSQL_USER=river
            - MYSQL_PASSWORD=river

    redis:
        image: redis:alpine
