image: sroze/drone-symfony
env:
    - COMPOSER_HOME=/tmp/composer
    - DATABASE_PASSWORD=''
    - DATABASE_HOST=127.0.0.1
    - DATABASE_USER=postgres
script:
    - composer self-update

    # Install dependencies
    - composer config -g github-oauth.github.com d5e0f6092daa83a33bcb439bfa88ecb87dc4c691
    - composer install

    # Run tests
    - bin/phpspec run
    - bin/behat -f progress

    # Run smoke tests
    - psql -U $DATABASE_USER -h $DATABASE_HOST -c 'create database river;'
    - app/console doctrine:migrations:migrate --no-interaction
    - bin/behat -f progress --profile=smoke
services:
    - postgres
cache:
    - /tmp/composer
