environment_variables:
    - name: KEEN_PROJECT_ID
      value: 56572b8e90e4bd47230e1add
    - name: KEEN_WRITE_KEY
      value: 5d3a020fd710c5fd231394e8c2912a0cc50bf2142586ffdd13105b2f15cb525ded70fd3342a5ad7a273cd2e416cd777716264f3b8003ef1c193dbf737d02d5f85619df8ec4b29c780185b70cde839a7d93bcda17f6f2aa729a3cff4f24ff8031d39f70eafd604958409a5f99cc364586
    - name: BUILDER_URL
      value: http://eu--west1--b-builder-continuouspipe-io-arbp8o5f7a1t.runscope.net

pipelines:
    - name: Production
      condition: code_reference.branch == 'master'
      tasks: [ images, production, migrations ]
    - name: Feature branches
      condition: code_reference.branch != 'master'
      tasks: [ images ]

tasks:
    images:
        build:
            environment:
                - name: GITHUB_TOKEN
                  value: ${GITHUB_TOKEN}

            services:
                api:
                    image: docker.io/inviqasession/cp-river

    production:
        deploy:
            cluster: ${CLUSTER}
            environment:
                name: '"river-" ~ code_reference.branch'
                
            services:
                rabbitmq:
                    locked: true

                    deployment_strategy:
                        readiness_probe:
                            type: tcp
                            port: 5672

                blackfire:
                    locked: true

                api:
                    endpoints:
                        -
                            name: https
                            type: NodePort
                            ssl_certificates:
                                -
                                    name: continuouspipeio
                                    cert: ${WILDCARD_SSL_CERT}
                                    key: ${WILDCARD_SSL_KEY}

                    specification:
                        environment_variables: &ENV
                            - name: AUTHENTICATOR_URL
                              value: https://authenticator.continuouspipe.io
                            - name: LOGSTREAM_URL
                              value: https://api.logstream.continuouspipe.io
                            - name: LOGSTREAM_FRONTEND_URL
                              value: http://logstream.continuouspipe.io
                            - name: BUILDER_URL
                              value: ${BUILDER_URL}
                            - name: PIPE_URL
                              value: http://pipe-continuouspipe-io-12bhda8pihd6.runscope.net
                            - name: RIVER_UI_URL
                              value: https://ui.continuouspipe.io
                            - name: RIVER_HOST
                              value: river-continuouspipe-io-8h5eecqzu4bp.runscope.net
                            - name: KEEN_PROJECT_ID
                              value: ${KEEN_PROJECT_ID}
                            - name: KEEN_WRITE_KEY
                              value: ${KEEN_WRITE_KEY}
                            - name: SENTRY_DSN
                              value: http://a28df8b25bdb4b8eb1b335849fa7daad:9401ad376e8b4c54b0a1138bb8093b2c@sentry.tools.sroze.io/10
                            - name: DATABASE_HOST
                              value: 104.155.7.25
                            - name: DATABASE_USER
                              value: river
                            - name: DATABASE_PASSWORD
                              value: 138xHEqgD93lk
                            - name: TIDEWAYS_API_KEY
                              value: ${TIDEWAYS_API_KEY}
                            - name: BITBUCKET_OAUTH_KEY
                              value: ${BITBUCKET_OAUTH_KEY}
                            - name: BITBUCKET_OAUTH_SECRET
                              value: ${BITBUCKET_OAUTH_SECRET}
                            - name: K8S_WATCHER_URL
                              value: http://api.k8s-watcher-master.svc.cluster.local
                            - name: K8S_HEALTH_CHECKER_URL
                              value: http://app.chc-master.svc.cluster.local
                            - name: ZIPKIN_BASE_URL
                              value: http://zipkin.zipkin-master.svc.cluster.local:9411
                            - name: APP_USER_LOCAL
                              value: false
                            - name: STACK_RABBITMQ_HOST
                              value: rabbitmq.stack-master.svc.cluster.local

                    deployment_strategy:
                        readiness_probe:
                            type: http
                            port: 80
                            path: /

                worker:
                    specification:
                        accessibility:
                            from_cluster: false
                        source:
                            from_service: api
                        environment_variables:
                            <<: *ENV
                            1000:
                              name: START_NGINX
                              value: 'false'
                            1001:
                              name: START_PHP_FPM
                              value: 'false'
                            1002:
                              name: START_WORKER
                              value: 'true'

                tideways:
                    specification:
                        resources:
                            limits:
                                cpu: 50m
                                memory: 100Mi

                redis:
                    deployment_strategy:
                        readiness_probe:
                            type: tcp
                            port: 6379

                    specification:
                        resources:
                            requests:
                                cpu: 50m
                                memory: 100Mi
                            limits:
                                cpu: 250m
                                memory: 250Mi

                cron:
                    specification:
                        source:
                            from_service: api

                        environment_variables:
                            - name: START_NGINX
                              value: 'false'
                            - name: START_PHP_FPM
                              value: 'false'
                            - name: START_CRON
                              value: 'true'

                        accessibility:
                            from_cluster: false

                eventstore:
                    specification:
                        volumes:
                            - type: persistent
                              name: eventstore-volume
                              capacity: 5Gi
                              storage_class: default

                        volume_mounts:
                            - name: eventstore-volume
                              mount_path: /var/lib/eventstore

                        resources:
                            requests:
                                cpu: 50m
                                memory: 150Mi

                    deployment_strategy:
                        readiness_probe:
                            type: tcp
                            port: 2113

        filter:
            expression: 'code_reference.branch == "master" or "cp:tide" in pull_request.labels'

    migrations:
        run:
            cluster: ${CLUSTER}
            environment:
                name: '"river-" ~ code_reference.branch'
            image:
                from_service: api
            commands:
                - composer run-script update-parameters
                - php app/console doctrine:migrations:migrate --no-interaction

            environment_variables:
                <<: *ENV

        filter:
            expression: 'code_reference.branch == "master" or "cp:tide" in pull_request.labels'

notifications:
    inviqa_slack:
        slack:
            webhook_url: https://hooks.slack.com/services/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
