api:
    build: .
    volumes:
        - .:/app
    links:
        - database
        - rabbitmq
        - blackfire
        - tideways
        - redis
        - eventstore
    environment:
        - SENTRY_DSN=http://88f4608cec7f48cfbea4113626266785:ad54b9d69c984fc69e3933a961f434c2@sentry.tools.sroze.io/9
        - RIVER_UI_URL=http://localhost
        - AUTHENTICATOR_URL=https://authenticator-staging.continuouspipe.io
        - BUILDER_URL=https://builder.continuouspipe.io
        - PIPE_URL=https://pipe-staging.continuouspipe.io
        - LOGSTREAM_URL=https://api.logstream.continuouspipe.io
        - LOGSTREAM_FRONTEND_URL=http://logstream.continuouspipe.io
        - RIVER_URL=http://localhost:80/app_dev.php
        - TIDEWAYS_API_KEY=bq8W3cebnQNuKgQA
        - APP_USER_LOCAL=true
    expose:
        - 80
    ports:
        - 81:80
        - 444:443
worker:
    build: .
    volumes:
        - .:/app
    links:
        - database
        - rabbitmq
        - redis
        - tideways
        - eventstore
    expose:
        - 80
    environment:
        - SENTRY_DSN=http://88f4608cec7f48cfbea4113626266785:ad54b9d69c984fc69e3933a961f434c2@sentry.tools.sroze.io/9
        - AUTHENTICATOR_URL=authenticator_app.docker
        - BUILDER_URL=builder_api.docker/app_dev.php
        - PIPE_URL=pipe_api.docker/app_dev.php
        - LOGSTREAM_URL=https://logstream-api.docker
        - LOGSTREAM_FRONTEND_URL=https://logstream-frontend.docker
        - RIVER_URL=river_api.docker/app_dev.php
        - START_NGINX=false
        - START_WORKER=true
        - START_PHP_FPM=false

database:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: river
        MYSQL_USER: river
        MYSQL_PASSWORD: river
    expose:
        - 3306

rabbitmq:
    image: rabbitmq:3-management
    expose:
        - 15672
        - 5672

blackfire:
    image: blackfire/blackfire
    environment:
        - BLACKFIRE_CLIENT_ID=a8efba47-c659-49b2-9705-3f7208e145ce
        - BLACKFIRE_CLIENT_TOKEN=77ba61c55ac2a1e4674b9d93e4ebf3ed1212e6bd522906e90202a5089cb3d839
        - BLACKFIRE_SERVER_ID=15ccd640-cbd8-4109-b9d0-4a649ce22fcc
        - BLACKFIRE_SERVER_TOKEN=8dfcfac46dd73b2d9b786451120e59b54c4e493fa8db4564662f9156bf0d82ff
    expose:
        - 8707

tideways:
    image: docker.io/sroze/tideways
    expose:
        - 9135

redis:
    image: redis:alpine
    expose:
        - 6379

eventstore:
    image: docker.io/eventstore/eventstore:release-3.8.1
    environment:
        - EVENTSTORE_RUN_PROJECTIONS=None
    expose:
        - 2113
