api:
    build: .
    command: /app/docker/apache.sh
    volumes:
        - .:/app
    links:
        - database
        - rabbitmq
    environment:
        - SENTRY_DSN=http://88f4608cec7f48cfbea4113626266785:ad54b9d69c984fc69e3933a961f434c2@sentry.tools.sroze.io/9
        - RIVER_UI_URL=http://ui_ui.docker
        - AUTHENTICATOR_URL=authenticator_app.docker
        - BUILDER_URL=builder_api.docker/app_dev.php
        - PIPE_URL=pipe_api.docker/app_dev.php
        - LOGSTREAM_URL=https://logstream-api.docker
        - RIVER_URL=river_api.docker/app_dev.php
    expose:
        - 80

worker:
    build: .
    command: /app/docker/worker.sh
    volumes:
        - .:/app
    links:
        - database
        - rabbitmq
    expose:
        - 80
    environment:
        - SENTRY_DSN=http://88f4608cec7f48cfbea4113626266785:ad54b9d69c984fc69e3933a961f434c2@sentry.tools.sroze.io/9
        - AUTHENTICATOR_URL=authenticator_app.docker
        - BUILDER_URL=builder_api.docker/app_dev.php
        - PIPE_URL=pipe_api.docker/app_dev.php
        - LOGSTREAM_URL=https://logstream-api.docker
        - RIVER_URL=river_api.docker/app_dev.php

database:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: river
        MYSQL_USER: river
        MYSQL_PASSWORD: river
    expose:
        - 3306

rabbitmq:
    image: rabbitmq:3-management
    expose:
        - 15672
        - 5672
